version: '3.8'

services:
  cyberfox:
    build: .
    container_name: cyberfox
    privileged: true
    ports:
      - "3000:3000"
      - "6000:6000"
    volumes:
      - ./projects:/home/cyberfox/projects
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DISPLAY=:0

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_HOST=0.0.0.0:11434
      - OLLAMA_ORIGINS=*


  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "8080:8080" # Example port mapping
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  opencti:
    build:
      context: ./projects/opencti
    container_name: openctihost
    ports:
      - "2222:22" # SSH port
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    # Add any other configuration needed for OpenCTI here.

volumes:
  ollama_data:
