---
- name: Integrate ThreatFox Connector into OpenCTI
  hosts: openctihost
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3
    opencti_admin_email: cyberfox@system.git
    opencti_admin_password: masterpassword
    opencti_base_url: localhost
    opencti_port: 8181
    app_port: 8181
    rabbitmq_default_user: guest
    rabbitmq_default_password: guest
    elastic_memory_size: 4
    smtp_hostname: localhost
    opencti_admin_token: "{{ lookup('community.general.random_string') | ansible.builtin.to_uuid }}"
    connector_history_id: "{{ lookup('community.general.random_string') | ansible.builtin.to_uuid }}"
    connector_export_file_stix_id: "{{ lookup('community.general.random_string') | ansible.builtin.to_uuid }}"
    connector_export_file_csv_id: "{{ lookup('community.general.random_string') | ansible.builtin.to_uuid }}"
    connector_import_file_stix_id: "{{ lookup('community.general.random_string') | ansible.builtin.to_uuid }}"
    connector_export_file_txt_id: "{{ lookup('community.general.random_string') | ansible.builtin.to_uuid }}"
    connector_import_document_id: "{{ lookup('community.general.random_string') | ansible.builtin.to_uuid }}"
    threatfox_connector_id: "{{ lookup('community.general.random_string') | ansible.builtin.to_uuid }}"

  tasks:
    - name: Clone OpenCTI connectors repository
      git:
        repo: 'https://github.com/OpenCTI-Platform/connectors.git'
        dest: '/opt/opencti-connectors'
        version: 'master'

    - name: Ensure the ThreatFox directory exists
      ansible.builtin.file:
        path: "/opt/opencti/external-import/threatfox"
        state: directory

    - name: Copy ThreatFox specific files from cloned repo
      ansible.builtin.copy:
        src: "/opt/opencti-connectors/external-import/threatfox/"
        dest: "/opt/opencti/external-import/threatfox/"
        remote_src: yes

    - name: Template the ThreatFox Connector's .env
      template:
        src: "env.j2"
        dest: "/opt/opencti/external-import/threatfox/.env"

    - name: Download and install Go version of yq
      ansible.builtin.get_url:
        url: https://github.com/mikefarah/yq/releases/download/v4.27.2/yq_linux_amd64
        dest: /usr/local/bin/yq
        mode: '0755'

    - name: Insert ThreatFox service into docker-compose.yml using yq
      ansible.builtin.shell: |
        /usr/local/bin/yq eval '.services.threatfox = {"container_name": "threatfox", "image": "opencti/connector-threatfox:latest", "restart": "unless-stopped", "environment": {"OPENCTI_URL": "http://opencti:8181", "OPENCTI_TOKEN": "{{ opencti_admin_token }}", "CONNECTOR_ID": "{{ threatfox_connector_id }}", "CONNECTOR_TYPE": "EXTERNAL_IMPORT", "CONNECTOR_NAME": "ThreatFox", "CONNECTOR_SCOPE": "file:hash:md5,file:hash:sha1,file:hash:sha256,ipv4-addr,domain-name,url", "CONNECTOR_CONFIDENCE_LEVEL": 3, "CONNECTOR_UPDATE_EXISTING_DATA": true, "CONNECTOR_LOG_LEVEL": "info", "THREATFOX_INTERVAL": 300}}' -i /opt/opencti/docker-compose.yml


